### ISSUE TITLE
Blocked running first clojure example

### ISSUE THREAD

**Issue by rebcabin** [limist/literate-programming-examples#1]
In "simple-code-blocks.org," keyboarding 'C-c C-c' with point in first code block #(reduce \* (range 1 (inc %))) produces "Not connected" in the minibuffer, even after saying 'cider-jack-in.'  I have latest version of cider installed and can run and develop clojure in the usual way.  Would really love to do LP in clojure and would be grateful for your help getting this going.

EDIT: there may be something wrong with my .lein/profiles.clj; investigating ...

**Comment by nblumoe** [comment]
@rebcabin maybe it's worth checking http://orgmode.org/worg/org-contrib/babel/languages/ob-doc-clojure.html

Did you set CIDER as the Clojure backend for org mode babel? 

``` emacs
(setq org-babel-clojure-backend 'cider)
(require 'cider)
```

**Comment by rebcabin** [comment]
checking ... used recommendation from clojure contribution layer for spacemacs to use this .lein/profiles.clj

{:user {:plugins [[cider/cider-nrepl "0.9.0-SNAPSHOT"]
                  [refactor-nrepl "0.3.0-SNAPSHOT"]]
        :dependencies [[alembic "0.3.2"]
                       [org.clojure/tools.nrepl "0.2.7"]]}}

but it crashes starting the server:

Starting nREPL server via lein repl :headless...
error in process sentinel: nrepl-server-sentinel: Could not start nREPL server: Retrieving cider/cider-nrepl/0.9.0-SNAPSHOT/cider-nrepl-0.9.0-20150616.120440-43.pom from clojars
Retrieving refactor-nrepl/refactor-nrepl/0.3.0-SNAPSHOT/refactor-nrepl-0.3.0-20150401.112429-28.pom from clojars
Retrieving org/clojure/tools.nrepl/0.2.7/tools.nrepl-0.2.7.pom from central
Retrieving refactor-nrepl/refactor-nrepl/0.3.0-SNAPSHOT/refactor-nrepl-0.3.0-20150401.112429-28.jar from clojars
Retrieving cider/cider-nrepl/0.9.0-SNAPSHOT/cider-nrepl-0.9.0-20150616.120440-43.jar from clojars
Retrieving alembic/alembic/0.3.2/alembic-0.3.2.pom from clojars
Retrieving lein-as-resource/lein-as-resource/2.5.0/lein-as-resource-2.5.0.pom from clojars
Retrieving org/flatland/classlojure/0.7.0/classlojure-0.7.0.pom from clojars
Retrieving org/clojure/tools.nrepl/0.2.7/tools.nrepl-0.2.7.jar from central
Retrieving org/flatland/classlojure/0.7.0/classlojure-0.7.0.jar from clojars
Retrieving alembic/alembic/0.3.2/alembic-0.3.2.jar from clojars
Retrieving lein-as-resource/lein-as-resource/2.5.0/lein-as-resource-2.5.0.jar from clojars
Error loading refactor-nrepl.ns.clean-ns: clojure.lang.ArityException: Wrong number of args (2) passed to: StringReader, compiling:(abnf.clj:189:28)

**Comment by rebcabin** [comment]
This is better, but still not perfect
     [[cider/cider-nrepl "0.9.1"]
                  [refactor-nrepl "1.1.0"]]
still digging...

**Comment by rebcabin** [comment]
yep, set the backend variable and still seeing "Not connected."  This doesn't seem to be your issue, though.  Something messed up in my emacs, cider, nrepl configuration.  Sorry to have bothered you.
